name: benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name : install deps
      run : chmod +x * ; ./deps.sh
    - name : benchmark
      run : chmod +x * ; ./bench.sh