name: benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name : allow permission
      run : chmod u+r+x deps.sh bench.sh
    - name : install deps
      run : ./deps.sh
    - name : benchmark
      run : ./bench.sh